# .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------. 
#| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#| |  _________   | || |   _____      | || |    _______   | || |      __      | || |  _________   | || |  ____  ____  | |
#| | |_   ___  |  | || |  |_   _|     | || |   /  ___  |  | || |     /  \     | || | |_   ___  |  | || | |_  _||_  _| | |
#| |   | |_  \_|  | || |    | |       | || |  |  (__ \_|  | || |    / /\ \    | || |   | |_  \_|  | || |   \ \  / /   | |
#| |   |  _|  _   | || |    | |   _   | || |   '.___`-.   | || |   / ____ \   | || |   |  _|      | || |    \ \/ /    | |
#| |  _| |___/ |  | || |   _| |__/ |  | || |  |`\____) |  | || | _/ /    \ \_ | || |  _| |_       | || |    _|  |_    | |
#| | |_________|  | || |  |________|  | || |  |_______.'  | || ||____|  |____|| || | |_____|      | || |   |______|   | |
#| |              | || |              | || |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------' 

#Plugin Created by BlueFusion12

#NOTE: This plugin requires Spigot in order to use advanced particle effects
#If you do not have Spigot installed, adjusting the particle amount will have no
#effect and particles will appear different than if using Spigot!
#To download Spigot, visit: http://www.spigotmc.org

Powers:
    #Occasionally, when Elsafy is activated, interacting with blocks, players, items, etc. will result
    #in freezing of the surrounding area
    FreezeOnInteract:
        #Enables or Disables this feature
        enabled: true
        #Chance that an interact will result in freezing the surrounding area (1-100)
        probability: 10
        #Maximum radius of freezed area
        maxradius: 6
    #By Double Left-Clicking, the player can launch an ice blast that freezes the area it hits
    IceBlast:
        #Enables or Disables this feature
        enabled: true
        #Enable or Disable Particles when using IceBlast
        particles: true
        #If particles is enabled, this controls the amount of particles (Recommended 3-8)
        particleamount: 6
        #Apply wither effect when IceBlast hits an entity or Player (Beware the Frozen Heart!)
        applyfrozenheart: false
        #Amount of time (in milliseconds) a Player must wait until using IceBlast again
        cooldown: 1000
    #Walking over water causes the water to freeze and spread to adjacent water blocks.
    FreezeWater:
        #Enables or Disables this feature
        enabled: true
        #Freeze Rate (Recommended 6-20)
        freezerate: 10
    #NOTE: This feature requires WorldEdit to be installed!
    #By Double-clicking Spacebar then clicking Shift, an ice castle is created at your location
    CreateCastle:
        #Enables or Disables this feature
        enabled: true
        #Build Rate (Blocks per tick [Recommended 10-25]
        buildrate: 20
        #Enable or Disable Particles when using CreateCastle
        particles: true
        #If particles is enabled, this controls the amount of particles (Recommended 3-8)
        particleamount: 6
        #Amount of time (in seconds) a Player must wait until using CreateCastle again
        cooldown: 120
    #By Double Right-Clicking (with an item in your hand), a snowman is built at the location you are looking at
    BuildSnowman:
        #Enables or Disables this feature
        enabled: true
        #Amount of time (in milliseconds) a Player must wait until using CreateCastle again
        cooldown: 1000
    #Randomly, between 2-5 minutes, snow particles will swirl around the character
    SnowSwirling:
        #Enables or Disables this feature
        enabled: true
    #By Holding Shift and Double Left-Clicking, a pillar of snow is brought up at the location you are looking at
    SnowPillars:
        #Enables or Disables this feature
        enabled: true
        #Enable or Disable Particles when using SnowPillars
        particles: true
        #If particles is enabled, this controls the amount of particles (Recommended 3-8)
        particleamount: 6
        #Controls the chance this power has to fail. Setting this to 0 will disable occasional misfiring
        misfirerate: 10
        #Build Rate (Blocks per tick [Recommended 2-6]
        pillarbuildrate: 4
        #Amount of time (in milliseconds) a Player must wait until using SnowPillars again
        cooldown: 1000
    #By Looking up and Double Left-Clicking, a burst of snow is launched into the air, forming a snowflake.
    Snowflake:
        #Enables or Disables this feature
        enabled: true
        #Amount of time (in milliseconds) a Player must wait until using Snowflake again
        cooldown: 5000
    #Use the command /elsafy bridge to toggle the bridge. Then, when you walk, a bridge will be formed under you.
    #Toggle between the UP and DOWN items in your inventory to control the vertical direction of the bridge!
    Bridge:
        #Enables or Disables this feature
        enabled: true
        #Enable or Disable Particles when using Bridge
        particles: true
        #If particles is enabled, this controls the amount of particles (Recommended 3-8)
        particleamount: 4
#Adjusts settings for the Rollback engine. WARNING: Don't know what these settings mean? Don't touch em.
Rollback:
    #Enable or Disable the Rollback Engine
    enabled: true
    #Powers Enabled here will rollback over time (Supported: FreezeOnInteract, IceBlast, SnowPillars)
    RollbackOverTime:
        FreezeOnInteract: true
        IceBlast: true
        SnowPillars: true
    #Powers Enabled here will rollback when a player disables their Elsafy or the server stops (Supported: FreezeWater, CreateCastle, Bridge)
    RollbackAtEnd:
        FreezeWater: false
        CreateCastle: false
        Bridge: false
    #Time (in ticks) per rollback run (only affects rollback over time,,, this affects speed of rollback [lower=faster])
    TimePerRun: 10